### ISSUE TITLE
Improve Docker script

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/uma_publist#17]
Currently, we are mapping the folder from which the docker script is called to the container, see https://github.com/UB-Mannheim/publist4ubma2/blob/master/tools/start-docker.sh#L43. Better would be to calculate this path according to the directory the script lies in.

**Comment by sebeka** [comment]
Hi Philipp, what you mean?

**Comment by zuphilip** [comment]
I will do this, this is just a reminder for me.
