### ISSUE TITLE
Vendor name in composer.json

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/uma_publist#18]
Copy this from https://github.com/UB-Mannheim/publist4ubma2/pull/14#discussion_r127057402 in composer.json: 

>> "name": "ubmannheim/publist4ubma2",

> @zuphilip: We could choose here also another vendor name like `ub-mannheim` or maybe `unima`. What do you think? We should then just make sure we can get a hold in in packagist.

> @sebeka: Yes, I think `unima` would be better, because ubmannheim belongs to unima in my opinion.
Thank you for the composer, haven't heard about it jet.

> @stweil: Is there a reason why we should use a short name? Otherwise I'd prefer a longer name like `uni-mannheim`.

**Comment by zuphilip** [comment]
Okay, a name representing the University of Mannheim is fine for me. I don't care that much about the exact string, it should be something which is easy to type. `unima` might be ambiguous. I am fine with Stefan's suggestion `uni-mannheim`, which is also the url domain of the university.

**Comment by zuphilip** [comment]
@sebeka Should we change to `uni-mannheim`?

**Comment by sebeka** [comment]
would be fine, thanks
