### ISSUE TITLE
Render publication list according to a specific citation style

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/uma_publist#20]
I had just a feature request to render the publication list accordingly to the APA 6th edition. We should be able to render the citations closely to APA style with another style file.

Another way would be to map the data to [CSL JSON](https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html) and then use [citeproc-js](https://citeproc-js.readthedocs.io/en/latest/) for rendering the publication list with the [citation style language (CSL)](http://citationstyles.org/).

**Comment by sebeka** [comment]
Hi,

I would prefer the Fluid style files because this is the typo3 way.

Otherwise (with js) it would have to work like:
- one Fluid Template for all possible Templates outputting always the same JSON
- citeproc-js is rendering all the different "Views"
-> think is to much work and is relaying on Java Script

**Comment by zuphilip** [comment]
Yes, I agree. As far as we can live with a good enough approximation of APA style, then I think we can for the first way.  For a very accurate and detailed APA implementation and possible other commons citations styles, we should consider CSL, for example APA style in CSL becomes quite complex: http://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fapa

I just found that we already have an APA style file for the BWL:
https://github.com/UB-Mannheim/publist4ubma2/blob/master/Resources/Private/Partials/FrontendBWLapa.html

This looks pretty good, but some things we should fix:
* We should add the doi's whenever possible at the end in the form `https://doi.org/10....`.
* At the end of each citation, but before the doi, there is point `.`.
* The [script for rendering the initials](https://github.com/UB-Mannheim/publist4ubma2/blob/master/Resources/Private/Partials/RenderNamesShort.html) does not work correctly for multiple first names, e.g. `Selma C. Rudert` -> `S.C.` (no spaces between several initials) or `Anna-Katharina Praetorius` -> `A.-K.`
* Several authors are connected by commas and the symbol `&` instead of  the word `and/und` and before this symbol there has to be a comma independent of the language.
* The volume for journal articles has to be emphazised toghether with the journal title.
* (Issues are in same cases added after the volume in parenthesis, but this is quite complicated in APA.)
* The authors of a books are not shown, only the editors.
* After the editors there should be a `(Hrsg.)` resp. `(Eds.)`.
* We should replace three occurrences of `..` by a single `.`.
* In book chapter/conference proceeding etc. the name of the editors of the book are not reversed and separated by a comma `,` from the book title.

(For examples to these points, one can look at the publication in APA style here: http://paed-psych.uni-mannheim.de/unser_team/prof_dr_oliver_dickhaeuser/publikationen/ ).

Can we fix these issues also for the BWL or are there any reason they don't want them? I think I can work on this, also not at the moment.

**Comment by sebeka** [comment]
Is done imho.

**Comment by zuphilip** [comment]
Yeah, except for #22 and #25 but they have their own issue.
