### ISSUE TITLE
Add new field for doi

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/uma_publist#22]
The doi number is for example needed the APA style. Moreover, we should consider the doi for resolving the urls. Before we can use it in these places, we have to first extract it from the EPrint XML.

In EP3 XML this corresponds to `id_number`, e.g. http://ub-madoc.bib.uni-mannheim.de/cgi/export/eprint/42761/XML/madoc-eprint-42761.xml:
```xml
    <id_number>10.3389/fpsyg.2017.01326</id_number>
```

Where do we have to change something? I [searched for a similar field ubmaExtern](https://github.com/UB-Mannheim/publist4ubma2/search?utf8=%E2%9C%93&q=urlUbmaExtern+&type=) and guess that in all these files we have to add similar code for the new field doi. Is this enough? Will this involve any database changes?

**Comment by zuphilip** [comment]
The database structure is defined in the ext_tables.sql and thereby it seems to be a good idea to [search then also for the variant url_ubma_extern](https://github.com/UB-Mannheim/publist4ubma2/search?utf8=%E2%9C%93&q=url_ubma_extern&type=), which gives more places to add something for a new field. (Maybe, we can even document how to add a new field.)

**Comment by sebeka** [comment]
OK, I can add this field. Do you have an example from ep3 xml, how it could be parsed?

I wil test the current version in github in our test typo3 and add the stuff for the new database field there.

Sebastian

**Comment by zuphilip** [comment]
Cool thank you! If you push such changes to a different branch, then I can as well test it before merging.

**Comment by zuphilip** [comment]
I indicated an example in the first posting. What other example do you need?

**Comment by sebeka** [comment]
ah ok, thanks

**Comment by sebeka** [comment]
ok, is inside: http://test.dws.informatik.uni-mannheim.de/en/research/publications/

Can we meet this afternoon, and you show me, how I can merge this stuff?
There are a lot of modified files, and I'm not sure, how to use github correct.

We can also raise the version number and write all the changes to changelog (also yours maybe)

When today is not possible, I have time next wednesday at the ear least.

Thanks, Sebastian

**Comment by zuphilip** [comment]
Closed by #28 .
