### ISSUE TITLE
Are the HMTL partials for rendering names still used?

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/uma_publist#23]
Are the HTML partials for rendering names used somewhere? For the frontend publication list rather the `Classes\ViewHelpers` render PHP classes are used.

I.e. can we delete these files?
```
Resources/Private/Partials/RenderNameShort.html
Resources/Private/Partials/RenderNamesShort.html
Resources/Private/Partials/RenderNamesWithAnd.html
Resources/Private/Partials/RenderNamesWithAndRdfaSchema.html
Resources/Private/Partials/RenderNameWithAnd.html
Resources/Private/Partials/RenderNameWithAndRdfaSchema.html
```

**Comment by sebeka** [comment]
Yes, some Partials and Viewhelpers may be not used. During development I changed some stuff but kept some earlier versions.

I think we can delete not used files.

Sebastian

**Comment by zuphilip** [comment]
Yes, we should delete unused files. They will still be part of the version history and thereby backuped.

Do you know any other unused files?
