### ISSUE TITLE
Explain how to scheduling synchronizing task

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/uma_publist#26]
I don't know how this work, @BFallert mentioned it once shortly, but it would be nice if we can explain it as part of the README.

**Comment by sebeka** [comment]
You mean how to set it up in typo3? as admin?

**Comment by zuphilip** [comment]
I see for example a task for publist4ubma2 in the planer of typo3, but I don't know how to configure this:

![planer](https://user-images.githubusercontent.com/5199995/29557032-1b24d728-8728-11e7-8b3b-6f6ac8e8aa85.jpg)

**Comment by sebeka** [comment]
OK, I did this

**Comment by zuphilip** [comment]
Thank you very much!
