### ISSUE TITLE
Are ext_tables.sql, ExtensionBuilder.json still used?

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/uma_publist#30]
I saw in your PR #28 that you didn't have to update the files `ext_tables.sql`, `ExtensionBuilder.json` for adding new fields. Thus, I guess that these fields are maybe just used for starting a new extension? Are they still used somewhere? Or should we delete them?

**Comment by sebeka** [comment]
Hi,

sorry, I missed something to add to ext_tables.sql in my Pull Request.
I did this now directly in github. Now I have to make version 0.1.3 I guess ...

(Don't forget to update your tables in install tool after upgrade)

ExtensionBuilder.json is from the extension builder, I think we can delete this file.

Sebastian
