### ISSUE TITLE
Release 0.1.3

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/uma_publist#31]
I think we can still delete the first release 0.1.3 and then just keep the second release by correctly tagging it:

https://github.com/UB-Mannheim/publist4ubma2/releases/tag/v0.1.3 (Delete)
https://github.com/UB-Mannheim/publist4ubma2/releases/tag/v0.1.3-1 (Change to v0.1.3)

Should we?

**Comment by sebeka** [comment]
Thank you!
Did not know that this is possible!

Sebastian

**Comment by zuphilip** [comment]
Done.
