### ISSUE TITLE
Render link to EPrints ID for not MADOC

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/uma_publist#33]
Currently, the url which will be produced by taking the EPrints ID is simply rendered by concatenating with `http://ub-madoc.bib.uni-mannheim.de/`, e.g. the ID `131091` will produce a link to http://ub-madoc.bib.uni-mannheim.de/131091. However, for other EPrints this has to be different. The xml has besides the EPrints ID also the id, which is the url, and we could use that instead or additionally:

![ep3xml-ids](https://user-images.githubusercontent.com/5199995/30117598-f7086602-9320-11e7-9b9e-8f2edfdc6d10.jpg)

Do you have any preference how to do this?

**Comment by zuphilip** [comment]
This [line in PublicationControler.php](https://github.com/UB-Mannheim/publist4ubma2/blob/ad7128394b6b1ea0746309ad2a291d0fb49d2d9a/Classes/Controller/PublicationController.php#L93) seems to calculate this url from the EPrints ID:
```php
$URL = $this->settingsManager->configValue('extMgn/eprintidUrlPrefix') . '/' . $eprint_id;
```
Can we replace this and instead use the value of the attribute `id` of the `eprint` node? How??

**Comment by sebeka** [comment]
This is already build in. You have to configure publist4ubma2 in the extension manager, and change the field:
Prefix for Link URL to eprintid [basic.eprintidUrlPrefix]
At the moment, it is set to:
http://ub-madoc.bib.uni-mannheim.de

**Comment by zuphilip** [comment]
Okay, but this might make it less flexible. Currently one TYPO3 instance is tailored to show the entries of one EPrints system. More flexible would be to have the ability to choose the EPrints system in each plugin call individually. I tried this for the demo: http://bibtemp.bib.uni-mannheim.de/demo/ (temporary url). By using the url field in the advanced options this already works most of the times, but the urls build from the EPrints id are sometimes pointing to the wrong system.

Moreover, it would be helpful even for us in Mannheim to have the ability to include MADOC and MADATA data in the same webpage.

I guess that for building the url here this should be easily achievable. I don't know what this would mean for the synchronization process. I will reopen the issue, such that we can discuss further.

@sebeka Would it technically be possible to use the atribute value `id` of the `eprint` node instead in line 93 of the PublicationController.php? (I couldn't figure out how to do that...)

**Comment by sebeka** [comment]
Hi Philip,

at the moment, the complete code is designed to sync from only one eprints instance.
Taking the urls dynamically out of the xml might be a little step in the right direction for supporting multiple instances. But there would be much more to do.

Sebastian

PS: Try the debug-all table template to have a look at all synced attributes. If the url you need is missing, we would have to introduce an other attribute (like the id_number)

**Comment by zuphilip** [comment]
My problem is, that this is the attribute value of a node and not the text content of a node, which we have for all other variables...

**Comment by zuphilip** [comment]
The xml is loaded here https://github.com/UB-Mannheim/publist4ubma2/blob/9f71267a08cc1989df973d1443c0226915b11ef7/Classes/Controller/PublistController.php#L273-L282 with the function xmlToArray https://github.com/UB-Mannheim/publist4ubma2/blob/60f0e29027a1a780b195a10c80d13c8d1fb20281/Classes/Utility/xmlUtil.php#L20-L30

It should be possible to add here also something for an attribute.. I will look into this...

**Comment by sebeka** [comment]
Great Job! is merged
