### ISSUE TITLE
Naming of the zip files in the releases

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/uma_publist#34]
It seems that the manually added zip files in the releases have to be named exactly as the plugin name, i.e. `publist4ubma2.zip`, to work with TYPO3.

**Comment by sebeka** [comment]
Yes, I zipped them myself after downloading.
The content of the directory "publist4ubma2" have to be zipped, but not the directory itself

Was this only a question, or is there something to do? Should we close this issue?

**Comment by zuphilip** [comment]
After the recent releases I added the zip with the content at this time to GitHub, but it seems that the name cannot be choosen freely: https://github.com/UB-Mannheim/publist4ubma2/releases e.g. the [zip for v0.1.3](https://github.com/UB-Mannheim/publist4ubma2/releases/download/v0.1.3/typo3plugin_publist4ubma2_v0.1.3.zip)

I can replace these files with the same files renamed each of them to `publist4ubma2.zip` and in the future keep also this name. I try to do this in the next days...

**Comment by stweil** [comment]
Philipp, I just fixed the names of the three TYPO3 zip files.

**Comment by zuphilip** [comment]
Wow, thank you 🙇 !
