### ISSUE TITLE
Variant for ISSN

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/uma_publist#36]
There is a variant for ISSN information in EP3 XML:
```xml
<issn>
   <item>1550-235X</item>
   <item>1098-0121</item>
</issn>
```
See e.g. [this query in Regensburg](https://epub.uni-regensburg.de/cgi/search/archive/advanced/export_epub_XMLCit.xml?dataset=archive&screen=Search&_action_export=1&output=XMLCit&exp=0%7C1%7C-date%2Fcreators_name%2Ftitle%7Carchive%7C-%7Ccreators_name%3Acreators_name%3AALL%3AEQ%3ADeinzer%2C+Gernot%7Ctype%3Atype%3AANY%3AEQ%3Aarticle+book_section+monograph+conference_item+book%7C-%7Ceprint_status%3Aeprint_status%3AANY%3AEQ%3Aarchive%7Cmetadata_visibility%3Ametadata_visibility%3AANY%3AEQ%3Ashow&n=&cache=14445623).

**Comment by sebeka** [comment]
Perfect, Thanks!
