### ISSUE TITLE
Make MADOC variable ubma_university available in the plugin

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/uma_publist#66]
For thesis the variable `ubma_university` is needed to correctly cite in APA style, see #65. E.g. https://madoc.bib.uni-mannheim.de/54296/

**Comment by zuphilip** [comment]
@lsuma Can you do that?

**Comment by lsuma** [comment]
Variable has been added and is now outputted for doctoral dissertations in Frontend APA layout. The term "doctoral dissertation" is shown in the active language.
