### ISSUE TITLE
Extend RenderNamesApaViewHelper.php with parameter inverted

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/uma_publist#67]
@lsuma Can you extend the render function in https://github.com/UB-Mannheim/uma_publist/blob/master/Classes/ViewHelpers/RenderNamesApaViewHelper.php such that it contains a new paremter inverted? Default value should be TRUE such that without mentioning the variable explicitely we invert the name parts. This should then produce for the name "Kiel, Heinrich" the following output:
- `n:renderNamesApa somebody="{publication.editors} inverted=TRUE` --> Kiel, H (default option)
- `n:renderNamesApa somebody="{publication.editors} inverted=FALSE` --> H. Kiel

The second option is needed for the editors of the book a chapters is in, see the example in #61.

**Comment by lsuma** [comment]
Parameter has been added as "nonInverted" and is now used in Frontend APA template. Using false as the default value for boolean values is less prone to accidental misuse.
