### ISSUE TITLE
Chapter in multi-volume book: Volume not in the parenthesis

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/uma_publist#68]
Currently, for a chapter in a multi-volume book the volume number is not in the parenthesis, e.g. https://madoc.bib.uni-mannheim.de/17367/ we have

```diff
Buchheim, C. (1992).
Deutschland und die Weltwirtschaft.
In T. Ohnishi (Hrsg.),
+Die Bundesrepublik Deutschland (Bd. 2, S. 101–117).
-Die Bundes­republik Deutschland Bd. 2 ( S. 101–117).
Tokyo: Waseda Univ. 
```

I am not sure why this does not work as it should be already in the code from #61. Here the variable `separateVolumeTitle` should be FALSE and therefore the other block should be outputed. However, it seems that this is not the case...

**Comment by lsuma** [comment]
Has been fixed. The condition for settings `separateVolumeTitle` contained syntax errors and did not use the correct function for string length.
