### ISSUE TITLE
Entries without a year don't show up

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/uma_publist#8]
Usually every entry has a publication year, but in [some rare cases](https://ub-madoc.bib.uni-mannheim.de/view/year/NULL.html) this is not true. Moreover, we don't find the year currently in other EPrints because we use a special field `ubma_date_year` for that instead of the `date` field.

Entries without a year don't show up currently! I guess that somehow the year and the entry type are special, because they are sometimes also determining the look and feel of the plugin.

Test example for this behavior: Enter `https://ub-madoc.bib.uni-mannheim.de/cgi/export_redirect?dataobj=8344&format=XML` in the `Query-URL` in the `Expert` mode.

**Comment by sebeka** [comment]
Hi Philip,

good issue, but year = 0 could create other problems, please check:
- in cases where a year menu is rendered, you have to filter and change the "0" to something 
  meaningful  in the fluid templates:
  - case 1: http://dws.informatik.uni-mannheim.de/en/people/professors/profdrheinerstuckenschmidt/
  - case 2: http://www.bib.uni-mannheim.de/publikationen/

files: Resources/Private/Partials/YearItem.html and Resources/Private/Partials/YearMenu.html

Please check in Classes/Controller/PublistController.php in function listOfYears($content) that everything works.
Maybe try out all combinations of Menus please.

Thanks for for your work!

Sebastian

**Comment by zuphilip** [comment]
Okay, @stweil and I discussed this issue and it was much easier now to set the year to `9999`, see my PR. I tested all combinations and they look fine.

**Comment by sebeka** [comment]
Hi Philip,

I talked to Mrs. Schimpf this morning. The missing year in PubID 8344 was a bug in madoc, she changed it to "2006" now.
https://ub-madoc.bib.uni-mannheim.de/8344/

She told me, that she would like to check every case, with a missing year, if she gets a list of that publications. At the moment Alexander is not at University, and I'm not able to do this.
Can you get such a list out of madoc? (Can we bother Bettina K. whit this?)

If she has checked it, and there are still publications without years which makes sense, than we should think about supporting this case.

**Comment by zuphilip** [comment]
Yes, I can handle the remaining task from here and talk to the people. Thank you very much!
